CREATE TABLE IF NOT EXISTS todos (
   id INTEGER PRIMARY KEY AUTOINCREMENT,
   name TEXT NOT NULL,
   description TEXT NOT NULL,
   date DATE DEFAULT CURRENT_DATE,
   done BOOLEAN NOT NULL DEFAULT false
)
